#!/usr/bin/env python3
"""Generate and validate aoa-session-memory decision lookup indexes."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[1]
DECISIONS_DIR = Path("docs/decisions")
INDEXES_DIR = DECISIONS_DIR / "indexes"
CONTRACT_PATH = INDEXES_DIR / "index_contract.yaml"
RECORD_GLOB = "AOA-SM-D-*.md"
DECISION_ID_RE = re.compile(r"AOA-SM-D-\d{4}")
DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
EXEMPT_TOP_LEVEL = {"AGENTS.md", "README.md", "TEMPLATE.md"}
GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_decision_indexes.py; "
    "do not edit by hand. -->"
)
REQUIRED_METADATA = (
    "decision_id",
    "original_date",
    "owner_surfaces",
    "surface_classes",
    "projection_layers",
    "guard_families",
    "posture",
)
GENERATED_PATHS = (
    INDEXES_DIR / "README.md",
    INDEXES_DIR / "by-number.md",
    INDEXES_DIR / "by-date.md",
    INDEXES_DIR / "by-surface.md",
    INDEXES_DIR / "by-projection-layer.md",
    INDEXES_DIR / "by-guard.md",
)


@dataclass(frozen=True)
class DecisionRecord:
    decision_id: str
    title: str
    status: str
    original_date: str
    owner_surfaces: tuple[str, ...]
    surface_classes: tuple[str, ...]
    projection_layers: tuple[str, ...]
    guard_families: tuple[str, ...]
    posture: str
    relative_path: Path


def normalize_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.strip().casefold()).strip("_")


def split_values(value: str) -> tuple[str, ...]:
    items = []
    for raw in value.split(","):
        item = raw.strip().strip("`").strip()
        if item and item not in items:
            items.append(item)
    return tuple(items)


def section_body(text: str, heading: str) -> str:
    match = re.search(
        rf"^##\s+{re.escape(heading)}\s*$\n(?P<body>.*?)(?=^##\s+|\Z)",
        text,
        flags=re.MULTILINE | re.DOTALL,
    )
    return match.group("body").strip() if match else ""


def parse_metadata(text: str) -> dict[str, str]:
    body = section_body(text, "Index Metadata")
    metadata: dict[str, str] = {}
    for line in body.splitlines():
        match = re.match(r"^-\s+([^:]+):\s*(.*?)\s*$", line)
        if match:
            metadata[normalize_key(match.group(1))] = match.group(2).strip()
    return metadata


def parse_record(repo_root: Path, path: Path) -> tuple[DecisionRecord | None, list[tuple[str, str]]]:
    relative_path = path.relative_to(repo_root)
    location = relative_path.as_posix()
    issues: list[tuple[str, str]] = []
    text = path.read_text(encoding="utf-8")

    title_match = re.search(r"^#\s+(.+?)\s*$", text, flags=re.MULTILINE)
    title = title_match.group(1).strip() if title_match else ""
    if not title:
        issues.append((location, "missing level-one decision title"))

    metadata = parse_metadata(text)
    for key in REQUIRED_METADATA:
        if not metadata.get(key):
            issues.append((location, f"missing Index Metadata field: {key}"))

    decision_id = metadata.get("decision_id", "")
    if not DECISION_ID_RE.fullmatch(decision_id):
        issues.append((location, "Decision ID must match AOA-SM-D-####"))
    expected_prefix = f"{decision_id}-" if decision_id else ""
    if expected_prefix and not path.name.startswith(expected_prefix):
        issues.append((location, "filename prefix must exactly match Decision ID"))
    if not re.fullmatch(r"AOA-SM-D-\d{4}-[a-z0-9][a-z0-9-]*\.md", path.name):
        issues.append((location, "decision filename must use full canonical ID and a lowercase slug"))

    original_date = metadata.get("original_date", "")
    if not DATE_RE.fullmatch(original_date):
        issues.append((location, "Original date must match YYYY-MM-DD"))

    status_body = section_body(text, "Status")
    status = next((line.strip().rstrip(".") for line in status_body.splitlines() if line.strip()), "")
    if not status:
        issues.append((location, "missing non-empty Status section"))

    required_sections = (
        "Context",
        "Options Considered",
        "Decision",
        "Rationale",
        "Consequences",
        "Boundaries",
        "Source Surfaces",
        "Follow-Up Route",
        "Verification",
    )
    for heading in required_sections:
        if not section_body(text, heading):
            issues.append((location, f"missing or empty section: {heading}"))

    if issues:
        return None, issues

    return (
        DecisionRecord(
            decision_id=decision_id,
            title=title,
            status=status,
            original_date=original_date,
            owner_surfaces=split_values(metadata["owner_surfaces"]),
            surface_classes=split_values(metadata["surface_classes"]),
            projection_layers=split_values(metadata["projection_layers"]),
            guard_families=split_values(metadata["guard_families"]),
            posture=metadata["posture"].strip(),
            relative_path=relative_path,
        ),
        [],
    )


def validate_contract(repo_root: Path) -> list[tuple[str, str]]:
    path = repo_root / CONTRACT_PATH
    location = CONTRACT_PATH.as_posix()
    if not path.is_file():
        return [(location, "missing decision index contract")]
    text = path.read_text(encoding="utf-8")
    required_lines = {
        "schema_version: aoa_session_memory_decision_index_contract_v1",
        "authority: docs/decisions/AGENTS.md",
        "source_records: docs/decisions/AOA-SM-D-*.md",
        "generated_by: scripts/generate_decision_indexes.py",
        "modeled_surfaces: []",
    }
    required_lines.update(f"  - {path.as_posix()}" for path in GENERATED_PATHS)
    issues = []
    for line in sorted(required_lines):
        if line not in text.splitlines():
            issues.append((location, f"missing contract line: {line}"))
    return issues


def collect_records(repo_root: Path) -> tuple[list[DecisionRecord], list[tuple[str, str]]]:
    root = repo_root / DECISIONS_DIR
    issues: list[tuple[str, str]] = []
    if not root.is_dir():
        return [], [(DECISIONS_DIR.as_posix(), "missing decision directory")]

    for name in sorted(EXEMPT_TOP_LEVEL):
        if not (root / name).is_file():
            issues.append(((DECISIONS_DIR / name).as_posix(), "missing decision lane document"))

    records: list[DecisionRecord] = []
    seen_ids: set[str] = set()
    for path in sorted(root.glob(RECORD_GLOB)):
        record, record_issues = parse_record(repo_root, path)
        issues.extend(record_issues)
        if record is None:
            continue
        if record.decision_id in seen_ids:
            issues.append((record.relative_path.as_posix(), f"duplicate Decision ID: {record.decision_id}"))
        else:
            seen_ids.add(record.decision_id)
            records.append(record)

    for path in sorted(root.glob("*.md")):
        if path.name in EXEMPT_TOP_LEVEL or path.match(RECORD_GLOB):
            continue
        issues.append((path.relative_to(repo_root).as_posix(), "unmodeled top-level decision Markdown"))

    if not records:
        issues.append((DECISIONS_DIR.as_posix(), "no valid decision records found"))
    issues.extend(validate_contract(repo_root))
    return sorted(records, key=lambda item: item.decision_id), issues


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def display_link(record: DecisionRecord) -> str:
    relative = record.relative_path.relative_to(DECISIONS_DIR)
    return f"[{escape_cell(record.decision_id + ' ' + record.title)}](../{relative.as_posix()})"


def join_values(values: Iterable[str]) -> str:
    rendered = ", ".join(values)
    return escape_cell(rendered or "none")


def render_readme() -> str:
    return "\n".join(
        [
            "# Decision Lookup Indexes",
            "",
            GENERATED_NOTICE,
            "",
            "These files are generated read models from decision-note `Index Metadata`.",
            "Decision records own rationale; these indexes only make lookup cheaper.",
            "",
            "## Indexes",
            "",
            "- [By number](by-number.md)",
            "- [By date](by-date.md)",
            "- [By surface class](by-surface.md)",
            "- [By projection layer](by-projection-layer.md)",
            "- [By guard family](by-guard.md)",
            "",
        ]
    )


def record_row(record: DecisionRecord, *, include_facets: bool = True) -> str:
    cells = [
        display_link(record),
        record.original_date,
        escape_cell(record.status),
    ]
    if include_facets:
        cells.extend(
            [
                join_values(record.owner_surfaces),
                join_values(record.surface_classes),
                join_values(record.projection_layers),
                join_values(record.guard_families),
                escape_cell(record.posture),
            ]
        )
    cells.append(f"`{record.relative_path.as_posix()}`")
    return "| " + " | ".join(cells) + " |"


def render_number(records: list[DecisionRecord]) -> str:
    lines = [
        "# Decisions By Number",
        "",
        GENERATED_NOTICE,
        "",
        "| Decision | Date | Status | Owner surfaces | Surface classes | Projection layers | Guard families | Posture | Path |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(record_row(record) for record in records)
    return "\n".join([*lines, ""])


def render_date(records: list[DecisionRecord]) -> str:
    lines = [
        "# Decisions By Date",
        "",
        GENERATED_NOTICE,
        "",
        "| Date | Decision | Status | Path |",
        "| --- | --- | --- | --- |",
    ]
    for record in sorted(records, key=lambda item: (item.original_date, item.decision_id), reverse=True):
        lines.append(
            f"| {record.original_date} | {display_link(record)} | {escape_cell(record.status)} | "
            f"`{record.relative_path.as_posix()}` |"
        )
    return "\n".join([*lines, ""])


def render_facet(records: list[DecisionRecord], *, title: str, attribute: str) -> str:
    grouped: dict[str, list[DecisionRecord]] = {}
    for record in records:
        for value in getattr(record, attribute):
            grouped.setdefault(value, []).append(record)
    lines = [f"# Decisions By {title}", "", GENERATED_NOTICE, ""]
    for value in sorted(grouped, key=str.casefold):
        lines.extend(
            [
                f"## {value}",
                "",
                "| Decision | Date | Status | Path |",
                "| --- | --- | --- | --- |",
            ]
        )
        for record in sorted(grouped[value], key=lambda item: item.decision_id):
            lines.append(record_row(record, include_facets=False))
        lines.append("")
    return "\n".join(lines)


def render_indexes(records: list[DecisionRecord]) -> dict[Path, str]:
    return {
        INDEXES_DIR / "README.md": render_readme(),
        INDEXES_DIR / "by-number.md": render_number(records),
        INDEXES_DIR / "by-date.md": render_date(records),
        INDEXES_DIR / "by-surface.md": render_facet(records, title="Surface Class", attribute="surface_classes"),
        INDEXES_DIR / "by-projection-layer.md": render_facet(
            records, title="Projection Layer", attribute="projection_layers"
        ),
        INDEXES_DIR / "by-guard.md": render_facet(records, title="Guard Family", attribute="guard_families"),
    }


def check_indexes(repo_root: Path, rendered: dict[Path, str]) -> list[tuple[str, str]]:
    issues = []
    for relative_path, expected in rendered.items():
        path = repo_root / relative_path
        if not path.is_file():
            issues.append((relative_path.as_posix(), "generated decision index is missing"))
        elif path.read_text(encoding="utf-8") != expected:
            issues.append((relative_path.as_posix(), "generated decision index is stale"))
    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated indexes are missing or stale")
    parser.add_argument("--repo-root", type=Path, default=DEFAULT_REPO_ROOT, help="repository root")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    records, issues = collect_records(repo_root)
    rendered = render_indexes(records) if records else {}
    if args.check and not issues:
        issues.extend(check_indexes(repo_root, rendered))
    if issues:
        for location, message in issues:
            print(f"- {location}: {message}")
        return 1

    if args.check:
        print(f"[ok] {len(records)} decision records and {len(rendered)} generated indexes are current")
        return 0

    for relative_path, content in rendered.items():
        path = repo_root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"[ok] generated {len(rendered)} indexes from {len(records)} decision records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
